---
galaxy_info:
  role_name: authenticators
  author: Martin Slemr
  description: An Ansible Role to create authenticators in Automation Platform Gateway.
  company: Red Hat

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
  license: GPLv3

  min_ansible_version: 2.16.0

  platforms:
    - name: EL
      versions:
        - all

  galaxy_tags:
    - gateway
    - aap
    - configuration
    - authenticator
    - authenticators

dependencies: []
...
