---
argument_specs:
  main:
    short_description: An Ansible Role to create services on automation platform gateway.
    options:
      gateway_services:
        description: Data structure describing your services
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
            description: Name of the resource
          new_name:
            type: str
            description: Setting this option will change the existing name (looked up via the name field)
          description:
            type: str
            description: Description of the service
          api_slug:
            type: str
            description:
              - URL slug for the gateway API path for the Controller, Hub and EDA services
              - Gateway API route requires value "gateway", but the slug is not used
          http_port:
            description:
              - Name or ID referencing the Http Port
              - Required when creating a new Service
            type: str
          service_cluster:
            description:
              - Name or ID referencing the Service Cluster
              - Required when creating a new Service
            type: str
          is_service_https:
            type: bool
            default: false
            description: Set this to true if the service cluster requires HTTPS
          enable_gateway_auth:
            type: bool
            description: If false, the AAP gateway will not insert a gateway token into the proxied request
          service_path:
            type: str
            description:
              - URL path on the AAP Service cluster to route traffic to
              - Required when creating a new Service
          service_port:
            type: int
            description:
              - Port on the service to route traffic to
              - Required when creating a new Service
          node_tags:
            type: str
            description:
              - Comma separated string
              - Selects which (tagged) nodes receive traffic from this route
          order:
            type: int
            description: The order to apply the routes in lower numbers are first. Items with the same value have no guaranteed order
          state:
            default: "{{ gateway_state | default('present') }}"
            required: false
            type: str
            description: Desired state of the resource.

      # Async variables
      gateway_configuration_services_async_retries:
        default: "{{ gateway_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      gateway_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      gateway_configuration_services_async_delay:
        default: "{{ gateway_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      gateway_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      gateway_configuration_async_dir:
        default:
        required: false
        description: Sets the directory to write the results file for async tasks. The default value is set to `null` which uses the Ansible Default of `~/.ansible_async`.

      # No_log variables
      gateway_configuration_services_secure_logging:
        default: "{{ gateway_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values
          from elsewhere.
      gateway_configuration_secure_logging:
        default: true
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      gateway_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      gateway_hostname:
        default: None
        required: false
        description: URL to the automation platform gateway.
        type: str
      gateway_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the automation platform gateway's SSL certificate.
        type: str
      gateway_username:
        default: None
        required: false
        description: user on the automation platform gateway. Either username / password or oauthtoken need to be specified.
        type: str
      gateway_password:
        default: None
        required: false
        description: gateway user's password on the automation platform gateway. This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere
          and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      gateway_oauthtoken:
        default: None
        required: false
        description: gateway user's token on the automation platform gateway. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook.
          Either username / password or oauthtoken need to be specified.
        type: str
...
