objects:
  role:
    dispatch:
      description: An Ansible Role to call other roles to create objects on automation platform gateway.
      name: dispatch
      version_added: null
    settings:
      description: An Ansible Role to create settings on automation platform gateway.
      name: settings
      version_added: null
    users:
      description: An Ansible Role to create users on automation platform gateway.
      name: users
      version_added: null
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    settings:
      description: Modify automation platform gateway settings.
      name: settings
      namespace: ''
      version_added: null
    token:
      description: create, update, or destroy automation platform gateway tokens.
      name: token
      namespace: ''
      version_added: null
    user:
      description: Configure a gateway user.
      name: user
      namespace: ''
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.0.0