---
galaxy_info:
  role_name: service_keys
  author: Martin Slemr
  description: An Ansible Role to create service keys in automation platform gateway.
  company: Red Hat

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker
  license: GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

  min_ansible_version: "2.14"

  platforms:
    - name: EL
      versions:
        - all

  galaxy_tags:
    - gateway
    - aap
    - configuration
    - servicekey
    - servicekeys

dependencies: []
...
