---

# These are the default variables common to most gateway_configuration roles
# You shouldn't need to define them again and again but they should be defined
# gateway_hostname: "{{ inventory_hostname }}"
# gateway_token: ""
# gateway_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the service nodes
routes_list: []
routes_secure_logging: "{{ gateway_configuration_secure_logging | default(false) }}"
routes_async_retries: "{{ gateway_configuration_async_retries | default(30) }}"
routes_async_delay: "{{ gateway_configuration_async_delay | default(1) }}"
routes_enforce_defaults: "{{ gateway_configuration_enforce_defaults | default(false) }}"
...
