---
argument_specs:
  main:
    short_description: An Ansible Role to create service clusters on automation platform gateway.
    options:
      service_clusters_list:
        description: Data structure describing your service clusters
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
            description: Name of the resource
          new_name:
            type: str
            description: Setting this option will change the existing name (looked up via the name field)
          service_type:
            type: str
            description: |
              Type of service ["hub", "controller", "eda", "gateway"]
              Required when creating new Service Cluster
          state:
            default: "{{ gateway_state | default('present') }}"
            required: false
            type: str
            description: Desired state of the resource.
          outlier_detection_enabled:
            type: bool
            description: If true, outlier detection will be used to determine if a node is unhealthy and should be ejected from the cluster.
          outlier_detection_consecutive_5xx:
            type: int
            description: Number of consecutive 5xx responses to consider a node unhealthy.
          outlier_detection_interval_seconds:
            type: int
            description: The time interval between ejection analysis sweeps.
          outlier_detection_base_ejection_time_seconds:
            type: int
            description: The base time a node will be ejected for.
          outlier_detection_max_ejection_percent:
            type: int
            description: The maximum percent of nodes that can be ejected from the cluster.
          health_checks_enabled:
            type: bool
            description: If true, health checks will be used to determine if a node is healthy.
          health_check_timeout_seconds:
            type: int
            description: The time to wait for a health check to complete.
          health_check_interval_seconds:
            type: int
            description: The time between health check requests.
          health_check_unhealthy_threshold:
            type: int
            description: The number of consecutive failed health checks before a node is considered unhealthy.
          health_check_healthy_threshold:
            type: int
            description: The number of consecutive successful health checks before a node is considered healthy.

      # Async variables
      service_clusters_async_retries:
        default: "{{ gateway_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      gateway_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      service_clusters_async_delay:
        default: "{{ gateway_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      gateway_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      platform_configuration_async_dir:
        default: null
        required: false
        description: >
          Sets the directory to write the results file for async tasks.
          The default value is set to `null` which uses the Ansible Default of `~/.ansible_async`.


      # No_log variables
      service_clusters_secure_logging:
        default: "{{ gateway_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: >
          Whether or not to include the sensitive tasks from this role in the log.
          Set this value to `true` if you will be providing your sensitive values from elsewhere.
      gateway_configuration_secure_logging:
        default: true
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      gateway_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      gateway_hostname:
        default: None
        required: false
        description: URL to the automation platform gateway.
        type: str
      gateway_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the automation platform gateway's SSL certificate.
        type: str
      gateway_username:
        default: None
        required: false
        description: user on the automation platform gateway. Either username / password or oauthtoken need to be specified.
        type: str
      gateway_password:
        default: None
        required: false
        description: >
          Gateway user's password on the automation platform gateway.
          This should be stored in an Ansible Vault at vars/gateway-secrets.yml or elsewhere and called from a parent playbook.
          Either username / password or oauthtoken need to be specified.
        type: str
      gateway_oauthtoken:
        default: None
        required: false
        description: >
          Gateway user's token on the automation platform gateway.
          This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook.
          Either username / password or oauthtoken need to be specified.
        type: str
...
